Edge-Center/terraform-provider-edgecenter

edgecenter/resource_edgecenter_lblistener.go
- added the Terminated HTTPS protocol type
- fixed required field 'name' and client version
=> updated the listener create and update processes

edgecenter/data_source_edgecenter_reservedfixedip.go, edgecenter/test/resource_edgecenter_lblistener_test.go
Changed go client at reservedfixedip_datasource
Task: https://tracker.yandex.ru/CLOUDDEV-480
=> feat(CLOUDDEV-480): changed go client at reservedfixedip_datasource

go.mod, go.sum
https://tracker.yandex.ru/CLOUDDEV-574
=> fix(CLOUDDEV-574): up version go client to v2.0.22

go.mod, go.sum
https://tracker.yandex.ru/CLOUDDEV-581
=> fix(CLOUDDEV-581): fixed security group in instance resource

edgecenter/resource_edgecenter_baremetal.go, edgecenter/resource_edgecenter_floatingip.go, edgecenter/resource_edgecenter_instance.go, edgecenter/resource_edgecenter_lblistener.go, edgecenter/resource_edgecenter_lbmember.go, edgecenter/resource_edgecenter_lbpool.go, edgecenter/resource_edgecenter_loadbalancer.go, edgecenter/resource_edgecenter_loadbalancerv2.go, edgecenter/resource_edgecenter_network.go, edgecenter/resource_edgecenter_reservedfixedip.go, edgecenter/resource_edgecenter_router.go, edgecenter/resource_edgecenter_secret.go, edgecenter/resource_edgecenter_snapshot.go, edgecenter/resource_edgecenter_subnet.go, edgecenter/resource_edgecenter_volume.go, edgecenter/test/data_source_edgecenter_floatingip_test.go, edgecenter/test/data_source_edgecenter_lbpool_test.go, edgecenter/test/data_source_edgecenter_reservedfixedip_test.go, edgecenter/test/data_source_edgecenter_secret_test.go, edgecenter/test/helper_test.go, edgecenter/test/resource_edgecenter_lbmember_test.go, go.mod, go.sum
https://tracker.yandex.ru/CLOUDDEV-587
=> fix(CLOUDDEV-587): fixed timeouts

docs/resources/reservedfixedip.md, edgecenter/resource_edgecenter_reservedfixedip.go
Added information about what parameters are required for each type of reserved fixed IP
=> docs(CLOUDDEV-491): Populate description for reserved fixed ip params

docs/data-sources/floatingip.md, docs/resources/floatingip.md, edgecenter/data_source_edgecenter_floatingip.go, edgecenter/resource_edgecenter_floatingip.go, edgecenter/utils.go
removed the "Computed" field and added additional validation on port_id 
https://tracker.yandex.ru/CLOUDDEV-562
=> fix(CLOUDDEV-562): added possibility to unbind port_id

edgecenter/resource_edgecenter_network.go
https://tracker.yandex.ru/CLOUDDEV-641
=> fix(CLOUDDEV-641): added validation to network.type

docs/data-sources/lblistener.md, docs/resources/lblistener.md, edgecenter/data_source_edgecenter_lblistener.go, edgecenter/resource_edgecenter_lblistener.go, go.mod, go.sum
https://tracker.yandex.ru/CLOUDDEV-586
Добавил таймауты в Listener.
=> feat(CLOUDDEV-586): add timeouts to lb_listeners.

docs/data-sources/lb_l7policy.md, docs/data-sources/project.md, docs/index.md, docs/resources/lb_l7policy.md, docs/resources/project.md, edgecenter/data_source_edgecenter_project.go, edgecenter/utils.go, edgecenter/utils_project.go, examples/resources/edgecenter_project/resource.tf
https://tracker.yandex.ru/CLOUDDEV-831
=> fix(CLOUDDEV-831): fixed getProjectID func

.github/workflows/release.yml
https://tracker.yandex.ru/CLOUDDEV-833
=> Обновил go до 1.22.0 в  release.yml 

edgecenter/resource_edgecenter_securitygroup.go
https://tracker.yandex.ru/CLOUDDEV-836
=> feat(CLOUDDEV-836): fixed Metadata

docs/data-sources/instanceV2.md, docs/resources/instanceV2.md, edgecenter/data_source_edgecenter_instanceV2.go, edgecenter/resource_edgecenter_instanceV2.go
https://tracker.yandex.ru/CLOUDDEV-839
=> Fix/clouddev 839 delete addresses and last_updates fields

edgecenter/utils_instance.go
https://tracker.yandex.ru/CLOUDDEV-658
=> fix(CLOUDDEV-658): fix security groups assigning

edgecenter/resource_edgecenter_instance.go
https://tracker.yandex.ru/CLOUDDEV-900
=> docs(CLOUDDEV-900): fixed instance resource deprecation message

edgecenter/resource_edgecenter_baremetal.go
https://tracker.yandex.ru/CLOUDDEV-656
=> fix(CLOUDDEV-656): fix bm net type validation

edgecenter/resource_edgecenter_securitygroup.go
https://tracker.yandex.ru/CLOUDDEV-665
=> fix(CLOUDDEV-665): fix security group name updating

docs/resources/lifecyclepolicy.md, edgecenter/resource_edgecenter_lifecyclepolicy.go
https://tracker.yandex.ru/CLOUDDEV-651
=> fix(CLOUDDEV-651): fix schedule updating

.golangci.yml, Makefile
Task: https://tracker.yandex.ru/CLOUDDEV-941
=> refactor(CLOUDDEV-941): Use latest version golangci-lint

edgecenter/resource_edgecenter_baremetal.go, edgecenter/resource_edgecenter_subnet.go
Tasks:
- https://tracker.yandex.ru/CLOUD-1265
- https://tracker.yandex.ru/CLOUDDEV-670
=> Fix bare metal and subnet update 

docs/resources/instanceV2.md, edgecenter/resource_edgecenter_instanceV2.go, edgecenter/test/resource_edgecenter_subnet_test.go, edgecenter/utils_instance.go, go.mod, go.sum
Task:  https://tracker.yandex.ru/CLOUDDEV-1330
=> fix(CLOUDDEV-1330): Fix import VM via instanceV2

docs/resources/volume.md, edgecenter/resource_edgecenter_volume.go, go.mod, go.sum
Task: https://tracker.yandex.ru/CLOUDDEV-1232
=> feat(CLOUDDEV-1232): Add infra_ssd volume type

edgecenter/data_source_edgecenter_instance.go, edgecenter/resource_edgecenter_instance.go, edgecenter/test/data_source_edgecenter_instance_test.go, edgecenter/test/resource_edgecenter_instance_test.go, edgecenter/utils_instance.go
Task: https://tracker.yandex.ru/CLOUDDEV-1362
=> fix(CLOUDDEV-1362): Rollback instance v1

edgecenter/resource_edgecenter_securitygroup.go, edgecenter/resource_edgecenter_snapshot.go, edgecenter/utils_snapshot.go
Task: https://tasks.edgecenter.ru/browse/CLOUD-1044
=> fix(CLOUD-1044): Fix update metadata for security group and snapshot

docs/resources/cdn_resource.md, docs/resources/cdn_rule.md, edgecenter/resource_edgecenter_cdn_resource.go, edgecenter/resource_edgecenter_cdn_rule.go, examples/resources/edgecenter_cdn_resource/resource.tf, examples/resources/edgecenter_cdn_rule/resource.tf
=> fix secondaryHostnames

edgecenter/resource_edgecenter_floatingip.go
Task: https://tasks.edgecenter.ru/browse/CLOUDDEV-659
=> fix(CLOUDDEV-659): Fix floating ip assignment

edgecenter/resource_edgecenter_baremetal.go, edgecenter/test/resource_edgecenter_instance_port_security_test.go
Task: https://tasks.edgecenter.ru/browse/CLOUDDEV-670
=> fix(CLOUDDEV-670): Recreate baremetal instance if flavor changed

docs/resources/instanceV2.md, edgecenter/resource_edgecenter_instanceV2.go, go.mod, go.sum
Task: https://tasks.edgecenter.ru/browse/CLOUDDEV-2198
=> fix(CLOUDDEV-2198): Send only password for windows-base VM instance
